"""empty message

Revision ID: c68cc720adeb
Revises: f3dfebfe6f57
Create Date: 2020-09-02 13:33:34.049933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c68cc720adeb'
down_revision = 'f3dfebfe6f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_property', sa.Column('property_value', sa.Text(), nullable=False))
    op.drop_column('widget_property', 'valuefuck')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_property', sa.Column('valuefuck', mysql.TEXT(), nullable=False))
    op.drop_column('widget_property', 'property_value')
    # ### end Alembic commands ###
