"""empty message

Revision ID: dc1e5477a27e
Revises: 0de6e50c0251
Create Date: 2020-08-31 15:14:41.261255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1e5477a27e'
down_revision = '0de6e50c0251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clock', sa.Column('name', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'clock', ['name'])
    op.add_column('compliment', sa.Column('name', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'compliment', ['name'])
    op.add_column('mail', sa.Column('name', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'mail', ['name'])
    op.add_column('task', sa.Column('name', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'task', ['name'])
    op.add_column('twitter', sa.Column('name', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'twitter', ['name'])
    op.add_column('weather', sa.Column('name', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'weather', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather', type_='unique')
    op.drop_column('weather', 'name')
    op.drop_constraint(None, 'twitter', type_='unique')
    op.drop_column('twitter', 'name')
    op.drop_constraint(None, 'task', type_='unique')
    op.drop_column('task', 'name')
    op.drop_constraint(None, 'mail', type_='unique')
    op.drop_column('mail', 'name')
    op.drop_constraint(None, 'compliment', type_='unique')
    op.drop_column('compliment', 'name')
    op.drop_constraint(None, 'clock', type_='unique')
    op.drop_column('clock', 'name')
    # ### end Alembic commands ###
