"""empty message

Revision ID: f424ef4d9370
Revises: f0ce150c5d84
Create Date: 2020-09-15 21:04:46.545988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f424ef4d9370'
down_revision = 'f0ce150c5d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
